### ISSUE TITLE
Dynamic test generation

### ISSUE THREAD

**Issue by tli2** [cmu-db/peloton-test#8]
### How to demo:
- nose2
### Risk (0-10 ordinal): 
- 4
### Client value (0-10 ordinal): 
- 10
### Percentage complete: 
- 100
### Sprint: 
- 1
### Notes: 
- Tianyu
  - [here](http://eli.thegreenplace.net/2014/04/02/dynamically-generating-python-test-cases)
  - The idea is that we do not want to manually write all test cases. It would be cool if we write smaller things and the testing framework can pick those up and execute for us. We should look into how to do this with nose.

**Comment by gcramre** [comment]
- Idea
  - using string formatting set a available formatting options and randomly generate values for each position
  - example:
    - SELECT {0} {1} {2} FROM *table* {3} WHERE {4} {5} {6}

**Comment by tli2** [comment]
https://docs.google.com/document/d/12AJvy7-OBVJQ284EJXvv8PO-6vcy9g0AbOA4qXhElME/edit
